- targets:  # url;humanname;routing;switch
    - google.com;google.com;external;vivo
    - apple.com;apple.com;external;vivo
    - github.com;github.com;external;vivo
    - 192.168.15.1;roteador;local;vivo
    - 192.168.15.200;pi-hole;local;vivo