- targets:  # url;humanname;routing;switch
    - http://google.com;google.com;external;internetbox
    - http://apple.com;apple.com;external;internetbox
    - http://github.com;github.com;external;internetbox
    - http://192.168.15.1;roteador;local;internetbox
    - http://192.168.15.200;pi-hole;local;internetbox
